# Generated by Django 4.0.2 on 2022-02-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='car',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='car_id',
            new_name='listing_id',
        ),
    ]
