# Generated by Django 4.0.2 on 2022-02-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealers',
            options={'verbose_name_plural': 'Dealers'},
        ),
    ]
