# Generated by Django 4.0.2 on 2022-02-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('Car', 'Car'), ('classics', 'classics'), ('convertibles', 'convertibles'), ('Exotic & Luxury', 'Exotic & Luxury'), ('Minivans', 'Minivans'), ('Sports', 'Sports'), ('SUV', 'SUV'), ('Trucks', 'Trucks'), ('Vans', 'Vans')], default='Car', max_length=100)),
                ('cat_image', models.ImageField(upload_to='categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('county', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Murang', 'Murang'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Nairobi', 'Nairobi')], default='Nairobi', max_length=200)),
                ('town', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('make', models.CharField(choices=[('Tesla', 'Tesla'), ('Lamborghini', 'Lamborghini'), ('Jeep', 'Jeep'), ('Rolls Royce', 'Rolls Royce'), ('Mercedes Benz', 'Mercedes Benz'), ('Ferrari', 'Ferrari'), ('Maserati', 'Maserati'), ('Porsche', 'Porsche'), ('BMW', 'Subaru'), ('Acura', 'Acura'), ('Dodge', 'Dodge'), ('Toyota', 'Toyota'), ('Hyundai', 'Hyundai'), ('Apple', 'Apple'), ('Subaru', 'Subaru'), ('Bugatti', 'Bugatti')], default='Tesla', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('mpg', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=200)),
                ('car_details', models.TextField()),
                ('description', models.TextField()),
                ('usb_charger', models.BooleanField(default=False)),
                ('gps', models.BooleanField()),
                ('automatic', models.BooleanField()),
                ('sunroof', models.BooleanField()),
                ('apple_car_play', models.BooleanField()),
                ('all_wheel_drive', models.BooleanField()),
                ('bluetooth', models.BooleanField()),
                ('audio_input', models.BooleanField()),
                ('convertible', models.BooleanField()),
                ('child_seat', models.BooleanField()),
                ('longterm_car', models.BooleanField()),
                ('bike_rack', models.BooleanField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('car_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.category')),
            ],
            options={
                'verbose_name_plural': 'Cars',
                'ordering': ['-pk'],
            },
        ),
    ]
