# Generated by Django 4.0.2 on 2022-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.IntegerField(default=100000),
        ),
    ]
