# Generated by Django 4.0.2 on 2022-02-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cars_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='automatic',
        ),
        migrations.AddField(
            model_name='cars',
            name='engine',
            field=models.CharField(default=15, max_length=50),
            preserve_default=False,
        ),
    ]
