# Generated by Django 4.0.2 on 2022-02-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_alter_dealers_options'),
        ('cars', '0003_remove_cars_automatic_cars_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dealers.dealers'),
            preserve_default=False,
        ),
    ]
