# Generated by Django 4.0.2 on 2022-02-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_cars_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='fuel_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(default='petrol', max_length=50),
        ),
    ]
