# Generated by Django 4.0.2 on 2022-02-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_cars_fuel_capacity_cars_fuel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='mpg',
            new_name='mileage',
        ),
    ]
