# Generated by Django 4.0.2 on 2022-03-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_mpg_cars_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(choices=[('Tesla', 'Tesla'), ('Lamborghini', 'Lamborghini'), ('Jeep', 'Jeep'), ('Rolls Royce', 'Rolls Royce'), ('Mercedes Benz', 'Mercedes Benz'), ('Ferrari', 'Ferrari'), ('Maserati', 'Maserati'), ('Porsche', 'Porsche'), ('BMW', 'Subaru'), ('Acura', 'Acura'), ('Dodge', 'Dodge'), ('Toyota', 'Toyota'), ('Hyundai', 'Hyundai'), ('Apple', 'Apple'), ('Subaru', 'Subaru'), ('Bugatti', 'Bugatti'), ('Mazda', 'Mazda'), ('Suzuki', 'Suzuki')], default='Tesla', max_length=100),
        ),
    ]
