# Generated by Django 4.0.2 on 2022-03-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_cars_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(choices=[('Tesla', 'Tesla'), ('Lamborghini', 'Lamborghini'), ('Jeep', 'Jeep'), ('Rolls Royce', 'Rolls Royce'), ('Mercedes Benz', 'Mercedes Benz'), ('Ferrari', 'Ferrari'), ('Maserati', 'Maserati'), ('Porsche', 'Porsche'), ('BMW', 'Subaru'), ('Acura', 'Acura'), ('Dodge', 'Dodge'), ('Toyota', 'Toyota'), ('Hyundai', 'Hyundai'), ('Apple', 'Apple'), ('Subaru', 'Subaru'), ('Bugatti', 'Bugatti'), ('Mazda', 'Mazda'), ('Suzuki', 'Suzuki'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Volkswagen', 'Volkswagen'), ('Fiat', 'Fiat'), ('Mitsubishi', 'Mitsubishi'), ('Chevrolet', 'Chevrolet'), ('Bentley', 'Bentley'), ('Audi', 'Audi'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Jaguar', 'Jagura'), ('Alfa Romeo', 'Alfa Romeo'), ('Bugatti', 'Bugatti'), ('Lexus', 'Lexus'), ('Acura', 'Acura'), ('Aston Martin', 'Aston Martin'), ('KIA', 'KIA'), ('Volvo', 'Volvo'), ('GMC', 'GMC'), ('Audi', 'Audi'), ('Peugeot', 'Peugeot'), ('Lotus', 'Lotus'), ('Mini', 'Mini'), ('Genesis', 'Genesis'), ('Lincoln', 'Lincoln'), ('Infiniti', 'Infiniti'), ('Pontiac', 'Pontiac'), ('Saab', 'Saab'), ('Rolls-Royce', 'Rolls-Royce'), ('Renault', 'Renault'), ('Datsun', 'Datsun'), ('Isuzu', 'Isuzu'), ('Tata', 'Tata'), ('Hino', 'Hino'), ('Scania', 'Scania'), ('BYD', 'BYD'), ('Chery', 'Chery'), ('Toyota Century', 'Toyota Century'), ('Toyota Alphard', 'Toyota Alphard'), ('FAW', 'FAW'), ('Daimler', 'Daimler'), ('General Motors', 'General Motors'), ('SAIC', 'SAIC'), ('Geely', 'Geely')], default='Tesla', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(choices=[('Car', 'Car'), ('classics', 'classics'), ('convertibles', 'convertibles'), ('Exotic & Luxury', 'Exotic & Luxury'), ('Minivans', 'Minivans'), ('Sports', 'Sports'), ('SUV', 'SUV'), ('Trucks', 'Trucks'), ('Vans', 'Vans'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Station Wagon', 'Station Wagon'), ('Hatchback', 'Hatchback')], default='Car', max_length=100),
        ),
    ]
